name: Link Check

on:
  push:
    branches: [main, draft]
  schedule:
    - cron: '0 0 1 * *'   # 每月 1 号跑一次
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lychee Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress './**/*.md'
          fail: false
